/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminDispensingRouteImport } from './routes/admin.dispensing'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin.inventory.index'
import { Route as AdminInventoryAddRouteImport } from './routes/admin.inventory.add'
import { Route as AdminInventoryExpiryRouteImport } from './routes/admin.inventory.expiry'
import { Route as AdminInventoryLowStockRouteImport } from './routes/admin.inventory.low-stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDispensingRoute = AdminDispensingRouteImport.update({
  id: '/admin/dispensing',
  path: '/admin/dispensing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryAddRoute = AdminInventoryAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryExpiryRoute = AdminInventoryExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryLowStockRoute = AdminInventoryLowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => AdminInventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/inventory': typeof InventoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/dispensing': typeof AdminDispensingRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/inventory/add': typeof AdminInventoryAddRoute
  '/admin/inventory/expiry': typeof AdminInventoryExpiryRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/inventory': typeof InventoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/dispensing': typeof AdminDispensingRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/inventory/add': typeof AdminInventoryAddRoute
  '/admin/inventory/expiry': typeof AdminInventoryExpiryRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/inventory': typeof InventoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/dispensing': typeof AdminDispensingRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/inventory/add': typeof AdminInventoryAddRoute
  '/admin/inventory/expiry': typeof AdminInventoryExpiryRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/inventory'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/data'
    | '/admin/dispensing'
    | '/admin/health'
    | '/admin/inventory'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/'
    | '/admin/inventory/add'
    | '/admin/inventory/expiry'
    | '/admin/inventory/low-stock'
    | '/admin/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/inventory'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/data'
    | '/admin/dispensing'
    | '/admin/health'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin'
    | '/admin/inventory/add'
    | '/admin/inventory/expiry'
    | '/admin/inventory/low-stock'
    | '/admin/inventory'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/inventory'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/data'
    | '/admin/dispensing'
    | '/admin/health'
    | '/admin/inventory'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/'
    | '/admin/inventory/add'
    | '/admin/inventory/expiry'
    | '/admin/inventory/low-stock'
    | '/admin/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  InventoryRoute: typeof InventoryRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminDispensingRoute: typeof AdminDispensingRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminInventoryRoute: typeof AdminInventoryRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dispensing': {
      id: '/admin/dispensing'
      path: '/admin/dispensing'
      fullPath: '/admin/dispensing'
      preLoaderRoute: typeof AdminDispensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/add': {
      id: '/admin/inventory/add'
      path: '/add'
      fullPath: '/admin/inventory/add'
      preLoaderRoute: typeof AdminInventoryAddRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/expiry': {
      id: '/admin/inventory/expiry'
      path: '/expiry'
      fullPath: '/admin/inventory/expiry'
      preLoaderRoute: typeof AdminInventoryExpiryRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/low-stock': {
      id: '/admin/inventory/low-stock'
      path: '/low-stock'
      fullPath: '/admin/inventory/low-stock'
      preLoaderRoute: typeof AdminInventoryLowStockRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
  }
}

interface AdminInventoryRouteChildren {
  AdminInventoryAddRoute: typeof AdminInventoryAddRoute
  AdminInventoryExpiryRoute: typeof AdminInventoryExpiryRoute
  AdminInventoryLowStockRoute: typeof AdminInventoryLowStockRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
}

const AdminInventoryRouteChildren: AdminInventoryRouteChildren = {
  AdminInventoryAddRoute: AdminInventoryAddRoute,
  AdminInventoryExpiryRoute: AdminInventoryExpiryRoute,
  AdminInventoryLowStockRoute: AdminInventoryLowStockRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
}

const AdminInventoryRouteWithChildren = AdminInventoryRoute._addFileChildren(
  AdminInventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  InventoryRoute: InventoryRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDataRoute: AdminDataRoute,
  AdminDispensingRoute: AdminDispensingRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminInventoryRoute: AdminInventoryRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
